source 'http://rubygems.org'

ruby '2.2.3'
gem 'sinatra'
gem 'dm-core'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-migrations'
# gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'sinatra-reloader'
gem 'bcrypt'
